### ISSUE TITLE
Please publish the recently merged Angular 14 fix

### ISSUE THREAD

**Issue by thatsmeta** [salesforce/akita#1045]
### Is this a regression?

No

### Description

Okay, this library is obviously not actively maintained anymore, but can you please just publish the Angular 14 fix to npmjs so we can all update our projects before migrating to a different library?

### Do you want to create a pull request?

No

**Comment by Ketec** [comment]
This also affects angular 15 upgrades - you can no longer roll back TS to an older version.

Can someone trigger the build for this? Or is that only for the repo owner who seem to no longer visit this anymore?

**Comment by Ketec** [comment]
@NetanelBasal can someone trigger a new release for the changes?

**Comment by llorenspujol** [comment]
Is quite concerning the low activity this project is having in the last year...

Aside of that, the library still works, is just an annoying typing issue. You can work around it skipping lib check in the tsconfig:

```javascript
{
    // ...
    "compilerOptions": {
        // ...
        "skipLibCheck": true, 
        // ...
    },
    // ...
}
```

It is not ideal, but is still better than staying in an older Angular version.

I hope this project takes off again BTW.

Does this Salesforce re-branding affected the continuity of the project? @NetanelBasal

**Comment by Ketec** [comment]
this doesn't only disable lib check, unfortunately - the name is misleading.
It ignores all type declaration files - including ones in your own code/project.

**Comment by NetanelBasal** [comment]
I'm waiting for some answers from the company behind Akita. I'll consider a fork to ngneat if I'm not satisfied with them.

**Comment by NetanelBasal** [comment]
The repo is updated now. I'll release new versions soon.

**Comment by Ketec** [comment]
Is @datorama/akita still under your control or does it need salesforce credentials to publish?
A package name change can be quite disruptive (I scanned and there are 108 imports across 6 teams/libraries/modules).

**Comment by NetanelBasal** [comment]
I'm on it.

**Comment by Ketec** [comment]
I think something got mixed up now.

entity service now requires a minimum of     "@angular/core": ">= 15.0.0",
```

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@">= 15.0.0" from @datorama/akita-ng-entity-service@8.0.0
npm ERR! node_modules/@datorama/akita-ng-entity-service
npm ERR!   @datorama/akita-ng-entity-service@"^8.0.0" from the root project
```


So it's now incompatible with angular 14. And there is no version compatible with angular 14.

**Comment by NetanelBasal** [comment]
I think you can. You can use npm i --force for now.

**Comment by WynieCronje** [comment]
In `package.json` I added below `overrides`. For me it make sens for these 2 modules. Since library authors always takes a while before updating the dependencies on their side

![image](https://user-images.githubusercontent.com/4537265/211516521-9d09bb92-647d-4a98-b3e5-849ec0ac1f68.png)
