### ISSUE TITLE
docs site is outdated

### ISSUE THREAD

**Issue by Den-dp** [salesforce/akita#1048]
### Is this a regression?

No

### Description

I found that this change
https://github.com/salesforce/akita/commit/c9af3eae3a1cec9fba48760736124d26fc14486b#diff-063de01d03a31f525569c23f169fb1fafb9e36f02ee1e2decabcd871e0ca8591
is not available in the docs
https://opensource.salesforce.com/akita/docs/enhancers/devtools

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Done
