### ISSUE TITLE
Missing Configuration Changes For Angular 17

### ISSUE THREAD

**Issue by PythooonUser** [salesforce/akita#1077]
### Is this a regression?

No

### Description

When installing via `$ ng add @datorama/akita` the following error is shown:

> Could not find the project main file inside of the workspace config (src)

My best guess would be that under Angular 17 the `angular.json` config changed in a way that is not understood by Akita?

### Do you want to create a pull request?

No

**Comment by SH2015** [comment]
Same issue here, time to find a new state management framework,I think Akita is not catching up with angular new changes

**Comment by PythooonUser** [comment]
Actually, with 9d88135c13af0a4bc944d1b2e90943a9a46512c4 they officially announced that this project is no longer being maintained. Closing!
