### ISSUE TITLE
Entity store, select slice of entities

### ISSUE THREAD

**Issue by antonellopasella** [salesforce/akita#122]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I change a property in an element and then the subscription at selectAll::filterBy is alwais called

store..selectAll({
      filterBy: entity => entity.discovered === true
});

## Expected behavior
I need to get updates only if the discovered field is updated.

**Comment by danzrou** [comment]
selectAll will be fired on each update of your state. the filterBy property will only filter the entities which you receive - but it will still fire.
What do you mean by

>  I need to get updates only if the discovered field is updated.

If discovered property is per each entity - you need to check changes for all of those entities? or is it a global property?
