### ISSUE TITLE
better error message if forget creating StoreConfig

### ISSUE THREAD

**Issue by hiepxanh** [salesforce/akita#56]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x ] Other... Please describe:
</code></pre>

## Current behavior
![screen shot 2018-08-22 at 11 15 37 am](https://user-images.githubusercontent.com/16970990/44442539-fe349280-a5fc-11e8-9923-0a0bf004b84b.png)
if `@StoreConfig({ name: 'products' })` is missing when you creating store (extends from EntityStore). It will throw this errror, that is not helpful

## Expected behavior
1) it should throw better error like. "did you forget to create StoreConfig({}) ?"
2) it will be better if we have typescript error check that @storeConfig is must to have when creating Store file.

## Minimal reproduction of the problem with instructions
creating store file without @StoreConfig

## What is the motivation / use case for changing the behavior?
sometime, new people like me forget to creating it.

**Comment by NetanelBasal** [comment]
Thanks. This is a good suggestion. I will add it. BTW, you don't need to create the files by yourself; you have akita-schematics or akita-cli.

**Comment by hiepxanh** [comment]
thank you. I'm trying learning from scratch without akita-schiematics and will use it with my next production project.
