### ISSUE TITLE
Renaming the state folder when creating stores with schematics

### ISSUE THREAD

**Issue by Disane87** [salesforce/akita#578]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently there will be a folder `state` created everytime we use the schematics

## Expected behavior

Renaming the "base folder" or prevents it's creation like this:

- Renaming: `ng g af store-name --flat true -baseDirName store`
- Prevent creation: `ng g af store-name --flat true -noBaseDir`

## Minimal reproduction of the problem with instructions

Using the cli commands to create a new store

## What is the motivation / use case for changing the behavior?

We have our own folder structure which we want to keep.
Actually we need to move the content of the folders manually.

**Comment by theorlovsky** [comment]
@Disane87 Giving the following structure:
```
tmp
└── app
```

You can rename "base folder" using `--dirName` flag:
`ng g @datorama/akita:af store-name --flat --dirName store`
The result:
```
tmp
└── app
    └── store
        ├── store-name.store.ts
        └── ...
```

I know this one might not be perfect, but we're using it as a workaround. You can "prevent it's creation" by using the following pattern:
`ng g @datorama/akita:af store-name --flat --dirName app --path tmp`
The result:
```
tmp
└── app
    ├── store-name.store.ts
    └── ...
```
We created our own schematic that extends `@datorama/akita:af` to it to fit our needs.

**Comment by NetanelBasal** [comment]
Schematics were removed in the latest version.
