### ISSUE TITLE
RxJS Peer Dependency issue upgrading to Angular 13

### ISSUE THREAD

**Issue by mikesnare** [salesforce/akita#771]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When upgrading to Angular 13 which requires RxJS 7.4.0 I am getting the following warnings from `npm install`:

```
npm WARN @datorama/akita@6.2.0 requires a peer of rxjs@>= 6.1.0 < 7 but none is installed. You must install peer dependencies yourself.
npm WARN @datorama/akita-ngdevtools@6.0.0 requires a peer of rxjs@>= 6.1.0 < 7 but none is installed. You must install peer dependencies yourself.
```

## Environment
<pre><code>
Angular version: 13.0.0

For Tooling issues:
- Node version: v14.15.5
- Platform:  Mac
</code></pre>

I understand that Elf is the new hotness, but we can't migrate right now.  Any chance that versions of the Akita gems with support for RxJS > 7 could be released?

**Comment by NetanelBasal** [comment]
Yes, we can increase the peer requirement.

**Comment by NetanelBasal** [comment]
In the meantime you can use --force

**Comment by mikesnare** [comment]
Yup, did that to get by it.  Just wanted to see if we could avoid it.  Thanks!

**Comment by NetanelBasal** [comment]
Hmm, we already support it.

**Comment by NetanelBasal** [comment]
https://github.com/datorama/akita/blob/master/libs/akita/package.json#L34

**Comment by NetanelBasal** [comment]
Update Akita, please.

**Comment by mikesnare** [comment]
Sigh... apologies.  Thanks again.
