### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by Teebo** [salesforce/akita#777]
### Is this a regression?

Yes

### Description

After running `ng add @datorama/akita`

I get the below output.

```
The package @datorama/akita@7.0.1 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: Cannot find module 'bluebird'
Require stack:
- C:\Users\...\Development\appp\node_modules\@schematics\update\node_modules\pacote\extract.js
- C:\Users\...\Development\appp\node_modules\@schematics\update\node_modules\pacote\index.js  
- C:\Users\...\Development\appp\node_modules\@schematics\update\update\npm.js
- C:\Users\...\Development\appp\node_modules\schematics-utilities\dist\package_update\npm.js  
- C:\Users\...Development\appp\node_modules\schematics-utilities\dist\package_update\index.js
- C:\Users\...\Development\appp\node_modules\schematics-utilities\dist\index.js
- C:\Users\...\Development\appp\node_modules\@datorama\akita\schematics\ng-add\index.js      
- C:\Users\...Development\appp\node_modules\@angular-devkit\schematics\tools\export-ref.js  
- C:\Users\...\Development\appp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\...\Development\appp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\...\Development\appp\node_modules\@angular\cli\models\command-runner.js
- C:\Users\...\Development\appp\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\...\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
```

And I cannot run any Akita schematics

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/143822243-d6265843-732d-4d8a-9d7f-95e954b3abbf.png)

**Comment by Teebo** [comment]
OK I see, but do you have bluebird installed?

**Comment by NetanelBasal** [comment]
I created a new Angular project.

**Comment by Teebo** [comment]
OK, let me see what's wrong on my side, I will update and close the issue if it's something on my end

**Comment by Teebo** [comment]
I have installed bluebird: `npm i bluebird` and run `ng add @datorama/akita`.
It worked, I have uninstalled bluebird after that, 
I am not sure what's the issue as the error was also thrown in a new ng project.

**Comment by Teebo** [comment]
Should I close the issue?

**Comment by Amit775** [comment]
happend to me too, running `ng add ...` again (without installing bluebird) and its work

**Comment by kaname-png** [comment]
Same error

**Comment by keithotto** [comment]
Also getting this error. Created a fresh Angular 13 app with `ng new` then immediately followed up with `ng add @datorama/akita`. Get the missing bluebird module error.

**Comment by basit74** [comment]
I am also getting the same error when using Angular 13

**Comment by rohit-pathak** [comment]
+1 Same error with Angular 13 using `ng add @datorama/akita`.

**Comment by sibijohn72** [comment]
bump. Angular 13 using ng add @datorama/akita

**Comment by yousafraza39142** [comment]
Same error, I'm on angular version 13.2.0 and it gives same bluebird error when installed using ng add ...

**Comment by yousafraza39142** [comment]
![Screenshot from 2022-03-22 14-44-18](https://user-images.githubusercontent.com/31831225/159452462-1275ae10-bcb8-4d0c-aff3-9030cd3f130c.png)
Works after installing bluebird as dependency

**Comment by Teebo** [comment]
@yousafraza39142  why do I need to install bluebird for it to work?  What is bluebird for?

**Comment by Randle-Lanre** [comment]
I tried installing bluebird and then re-installing  akita, then i get  
![image](https://user-images.githubusercontent.com/19264390/160296526-20821929-0744-408f-8eb9-ca810900927d.png)

does anyone know if there's a patch for this

**Comment by jerosancho** [comment]
+1 Same error using `ng add` on Angular 13

**Comment by Randle-Lanre** [comment]
@jerosancho use npm to remove Akita,

ensure all imports/declarations related to Akita are removed from your app.module.ts 

then proceed to add the bluebird package and then akita.

this was the fix for my own issue

**Comment by NetanelBasal** [comment]
The repo is updated now. I'll release new versions soon.
