### ISSUE TITLE
@angular/core/core has no exported member 'InjectableDeclaration'

### ISSUE THREAD

**Issue by thomasgainant** [salesforce/akita#795]
### Is this a regression?

No

### Description

I am getting an error when I use the command **ng serve --o** using Akita on an Angular 11 project:

```
Error: node_modules/@datorama/akita-ngdevtools/lib/ng-devtools.module.d.ts:10:22 - error TS2694: Namespace '"F:/projectP/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

10     static ɵprov: i0.ɵɵInjectableDeclaration<AkitaDevtools>;
```

Before this, Akita was working on other projects. I just installed Akita on this new project. Is only the last version with this bug?

### Please provide a link to a minimal reproduction of the bug

Simply install Akita into an Angular project, using https://datorama.github.io/akita/docs/installation
Then use ng serve --o to get your dev server running

**Comment by thomasgainant** [comment]
Alright, I found a fix: I removed akita from my package.json and the dev tools from the dev dependencies in my package.json, deleted my npm_modules, redid a "npm install" and re-added Akita using "ng add @datorama/akita", this time saying "no" when asked to install the dev tools. Now it is working. Maybe something is wrong with the dev tools on some version of Angular.

**Comment by NetanelBasal** [comment]
The repo is updated now. I'll release new versions soon.
