### ISSUE TITLE
Installing akita downgrades @angular-devkit/* versions in nx

### ISSUE THREAD

**Issue by yonzmeer** [salesforce/akita#807]
### Is this a regression?

Yes

### Description

I created a new `nx-workspace` of version 13.9.2 with angular an nest in it.
The nx schematics work fine and `@angular-devkit/schematics` version in the `node_modules` is 13.2.6.

When adding akita, by running `npm i @datorama/akita`, the nx schematics stop to work properly:
`nx g @nrwl/angular:application` uses an old schematic and `@angular-devkit/schematics` in the `node_modules` drop to `8.3.29`.

The only way I found how to solve this, since working in an offline environment and using an offline npm registry, is to publish my own `schematics-utilities` with the latest versions of `@angular-devkit/*` packages in its `package.json`.

Minimal steps to reproduce (other then cloning the repo I'm providing):
```
npx create-nx-workspace@13.9.2
npm i @datorama/akita
rm -rf node_modules 
rm package-lock.json
npm i
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/yonzmeer/akita-and-nx

### Please provide the environment you discovered this bug in

```true
I'm using:
nx 13.9.2
angular 13.2.6
node 12.22.11 
npm 6.14.16
The problem occurs in windows 10, Debian 8 and ubuntu 20.
```

### Anything else?

I'm not sure if it's an nx or akita problem.
I tried the nrwl/nx slack community but without any success.
publishing the issue here since the only solution I found was to manually change one of akita's dependencies.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Schematics were removed in the new version.
