### ISSUE TITLE
high severity vulnerabilities

### ISSUE THREAD

**Issue by smichel-amiltone** [salesforce/akita#836]
### Is this a regression?

No

### Description

Npm report high severity vulnerabilitie

@datorama/akita:7.1.1 > "schematics-utilities": "^2.0.3" > @schematics/update@0.803.29 **(deprecated)** > "ini" : 1.3.5
 
ini  <1.3.6
Severity: high
Prototype Pollution - https://github.com/advisories/GHSA-qqgx-2p2h-9c37

### Please provide the environment you discovered this bug in

```true
Node 16, Npm 8.8, Angular 13
```

### Do you want to create a pull request?

No

**Comment by GoestaBergfeld** [comment]
Any update how to fix the problem?

**Comment by RonnieRocket147** [comment]
I would like to fix this too please

**Comment by Ketec** [comment]
https://github.com/nitayneeman/schematics-utilities/issues/49
https://www.npmjs.com/package/@schematics/update

Apparently, it uses deprecated packages so this entire package itself should be in turn considered deprecated.
That package is not maintained - the last update was years ago.

This may no longer be needed as it was acting as a "polyfill" for older angular versions.

**Comment by masatada-kurihara** [comment]
@NetanelBasal 
please confirm

**Comment by NetanelBasal** [comment]
The repo is updated now. I'll release new versions soon.
