### ISSUE TITLE
Re-add firebase-entity-service

### ISSUE THREAD

**Issue by randallmeeker** [salesforce/akita#838]
### Description

It looks like firebase-entity-service was removed here https://github.com/salesforce/akita/commit/2e9ca1755f6047c427ff21abf9d8e70e5c08c7ef#diff-6041bc2fbcd8cafdfceed312cca6f3604fc08afbda3bff4f4922ef48b32e6490L59

Is there a reason it was pulled and can it be added back in if I make a PR?

### Proposed solution

Is there a reason it was pulled and can it be added back in if I make a PR?

### Alternatives considered

live with it

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Schematics were removed in the latest version.
